name: worktoy_env
channels:
  - conda-forge
dependencies:
  - python>=3.14.2
  - pip>=24.0
  - setuptools>=69.5.1
  - wheel>=0.43.0
  - icecream>=2.1.8  # Development only
  - pytest>=9.0.2  # Development only
  - pytest-cov>=7.0.0  # Development only

#  Required by icecream
#    + asttokens    3.0.1  pyhd8ed1ab_0  conda-forge     Cached
#    + colorama     0.4.6  pyhd8ed1ab_1  conda-forge     Cached
#    + executing    2.2.1  pyhd8ed1ab_0  conda-forge     Cached
#    + icecream    2.1.10  pyhd8ed1ab_0  conda-forge     Cached
#    + pygments    2.19.2  pyhd8ed1ab_0  conda-forge     Cached


#  Required by pytest and pytest-cov
#  _openmp_mutex      4.5      20_gnu              conda-forge
#  colorama           0.4.6    pyhd8ed1ab_1        conda-forge
#  coverage           7.13.4   py314h67df5f8_0     conda-forge
#  exceptiongroup     1.3.1    pyhd8ed1ab_0        conda-forge
#  iniconfig          2.3.0    pyhd8ed1ab_0        conda-forge
#  libgcc             15.2.0   he0feb66_17         conda-forge
#  libgomp            15.2.0   he0feb66_17         conda-forge
#  packaging          26.0     pyhcf101f3_0        conda-forge
#  pluggy             1.6.0    pyhf9edf01_1        conda-forge
#  pygments           2.19.2   pyhd8ed1ab_0        conda-forge
#  pytest             9.0.2    pyhcf101f3_0        conda-forge
#  pytest-cov         7.0.0    pyhcf101f3_1        conda-forge
#  python             3.14.3   h32b2ec7_101_cp314  conda-forge
#  python_abi         3.14     8_cp314             conda-forge
#  tomli              2.4.0    pyhcf101f3_0        conda-forge
#  typing_extensions  4.15.0   pyhcf101f3_0        conda-forge